#Aprobacion manual
version: 2.1

jobs:
  saluda:
    docker:
      - image: cimg/base:stable
    steps:
      - run: hola #Quitando el echo para que falle el pipeline
  despidete:
    docker:
      - image: cimg/base:stable
    steps: #Los steps siempre se ejecuntan en serie
      - run: echo pre adios
      - run: echo adios
      - run: echo post adios

workflows:
  workflow1:
    jobs: #Los jobs se pueden ejecutar en paralelo o en serie porque no hay dependencia entre ellos
      - saluda
      - despidete
  workflow2:
    jobs: 
      - saluda
      - despidete:
          requires:
            - saluda
  workflow3: 
    jobs:
      - saluda
      - approval:
          type: approval
          requires:
            - saluda
      - despidete:
          requires:
            - approval