version: 2.1

jobs:
  saluda:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo hola
  despidete:
    docker:
      - image: cimg/base:stable
    steps: #Los steps siempre se ejecuntan en serie
      - run: echo pre adios
      - run: echo adios
      - run: echo post adios

workflows:
  hello:
    jobs: #Los jobs se pueden ejecutar en paralelo o en serie
      - saluda
      - despidete
